wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 3000:81
  volumes:
    - ~/wordpress/wp_html:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:81
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass